### ISSUE TITLE
Environment variables to configure for AWS Lambda client

### ISSUE THREAD

**Issue by jleclanche** [getsentry/sentry-docs#335]
https://docs.sentry.io/clients/python/integrations/lambda/

This says "Additional settings for the client are configured using environment variables" but it doesn't say what environment variables. Can this be added?

**Comment by untitaker** [comment]
See #375, I decided not to document the environment variables feature since this is something that we never wanted to encourage using, but had in raven for backwards compat. I hope this clears up things.

**Comment by jleclanche** [comment]
@untitaker I'm a little confused. This is my serverless.yml env var config:

```yml
provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  timeout: 300
  stage: ${opt:stage, "dev"}
  versionFunctions: false
  environment:
    SENTRY_DSN: ${env:SENTRY_DSN}
    SENTRY_RELEASE: ${env:CI_COMMIT_SHA}
    SENTRY_ENVIRONMENT: ${self:provider.stage}
```

And this is the code I use for my handlers:

```py
from raven.contrib.awslambda import LambdaClient

raven_client = LambdaClient()

@raven_client.capture_exceptions
def func(event, context):
    ...
```

Should I be doing something different?
